services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sistema_bancario
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Doctor@do0501
      SPRING_RABBITMQ_HOST: localhost
      SPRING_RABBITMQ_PORT: 5672
    networks:
      - backend

  mysql:
    image: mysql:latest
    ports:
      - "3308:3307"
    environment:
      MYSQL_ROOT_PASSWORD: Doctor@do0501
      MYSQL_DATABASE: sistema_bancario
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

networks:
  backend:
    driver: bridge
